# src/main/resources/application.properties

# Database (Neon Postgres)
spring.datasource.url=jdbc:postgresql://ep-calm-poetry-adtwx6yi-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_gLZJzbhx9W8r

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Mailjet (we will call the REST API)
mailjet.apiKey=a6e945940c5e274ec715eaece0efead7
mailjet.apiSecret=efa04c04857ac69349f76893b2b27b3b
mailjet.fromEmail=trainedbot10k@gmail.com
mailjet.fromName=TopperFriend

# Server port (optional)
server.port=8080

gemini.apiKey=AIzaSyCA1b2hc6x1gSLma-Xw7XxJ6RBf6hmeokY