# Database (Neon Postgres)
spring.datasource.url=jdbc:postgresql://ep-calm-poetry-adtwx6yi-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_gLZJzbhx9W8r

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Logging configuration
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN

# ENV Variables
mailjet.apiKey=a6e945940c5e274ec715eaece0efead7
mailjet.apiSecret=efa04c04857ac69349f76893b2b27b3b
mailjet.fromEmail=trainedbot10k@gmail.com
mailjet.fromName=TopperFriend
server.port=8080
gemini.apiKey=AIzaSyCA1b2hc6x1gSLma-Xw7XxJ6RBf6hmeokY